### ISSUE TITLE
Is this Kodi Live EU?

### ISSUE THREAD

**Issue by Djtrip83** [KodiLiveTV/KodiLiveTV.github.io#1]
Hi there! 

Not an issue.
Just checking if this is the same as or a fork of the "Kodi Live EU" IPTV Add-on?

Have a nice day

**Comment by KodiLiveTV** [comment]
It's the Official

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Djtrip83** [comment]
thanks
